runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: 0

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /sitemap.xml
  static_files: www/sitemap.xml
  upload: www/sitemap.xml

- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt

- url: /static/
  static_dir: static

- url: .*
  script: Promotion.app
