runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: 0d

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /BingSiteAuth.xml
  static_files: www/BingSiteAuth.xml
  upload: www/BingSiteAuth.xml
  secure: always

- url: /sitemap.xml
  static_files: www/sitemap.xml
  upload: www/sitemap.xml
  secure: always

- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt
  secure: always

- url: /static/
  static_dir: static
  secure: always

- url: /_ah/admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: Promotion.app
  secure: always
