runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: 0

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /static/
  static_dir: static

- url: .*
  script: Promotion.app
